server:
  port: 8080
  servlet.context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:my-board
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always
  h2.console.enabled: true